Add a simple Snowflake data quality pipeline
astronomer/airflow-data-quality-demo pull request #2
Opened 2021-08-19 20:51 UTC by denimalpaca

This pipeline is very similar to the Bigquery and Redshift EL 3 DAGs in structure and usage. It serves as an example to show how data quality can be added to a Snowflake DAG. It uses two operators, SnowflakeCheckOperator and SnowflakeValueCheckOperator, that do not currently exist in the Snowflake provider; a PR has been opened in Airflow to add these (https://github.com/apache/airflow/pull/17741).

2021-08-27 18:44 UTC, josh-fell requested changes

2021-08-27 18:44 UTC, josh-fell commented on dags/snowflake_examples/simple_snowflake_el.py
> +from airflow import DAG, AirflowException
Doesn't look like `AirflowException` nor `Variable` modules are used in this DAG. Can you remove these imports?

2021-08-27 18:44 UTC, josh-fell commented on dags/snowflake_examples/simple_snowflake_el.py
> +default_args = {
Can you update the `default_args` and `start_date` pattern to what we discussed in the Airflow/dbt guide comments?

2021-08-27 18:44 UTC, josh-fell commented on dags/snowflake_examples/simple_snowflake_el.py
> +    begin >> create_table >> load_data
Could these dependencies be simplified using `airflow.models.baseoperator.chain()`? Something like:

```
chain(begin, create_table, load_data, [quality_check_group, check_bq_row_count], delete_table, end)

2021-08-30 16:09 UTC, denimalpaca commented on dags/snowflake_examples/simple_snowflake_el.py
> +    begin >> create_table >> load_data
I didn't even know about `chain()`! Thanks for letting me know.

2021-08-31 16:04 UTC, josh-fell approved these changes

2021-08-31 16:05 UTC, merged